singleServerConfig:
  address: "redis://192.168.50.128:6379"
  password: 123456
  clientName: "client"
  database: 4
  connectTimeout: 10000
  retryAttempts: 3
  retryInterval: 1500
  connectionPoolSize: 64
  connectionMinimumIdleSize: 10